# Generated by Django 5.0.6 on 2024-07-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investimento_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('concluido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
