# Generated by Django 5.0.6 on 2024-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_planejamento_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='barra',
            field=models.IntegerField(default=20.0),
        ),
    ]
