# Generated by Django 5.0.6 on 2024-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_planejamento_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='barra',
            field=models.IntegerField(default=0.0),
        ),
    ]
