# Generated by Django 5.0.6 on 2024-07-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_remove_planejamento_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
