# Generated by Django 5.0.6 on 2024-07-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_planejamento_saldo_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='concluido',
        ),
    ]
