# Generated by Django 5.0.6 on 2024-07-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_remove_planejamento_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
