# Generated by Django 5.0.6 on 2024-07-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_planejamento_concluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_movimentacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('ganho', models.BooleanField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
