# Generated by Django 5.0.6 on 2024-07-14 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_movimentacoes_usuario_alter_movimentacoes_ganho'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
