# Generated by Django 5.0.6 on 2024-07-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_movimentacoes_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='valor_total_movimentacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
