# Generated by Django 5.0.6 on 2024-07-14 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_remove_movimentacoes_valor_total_movimentacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='PerfilUsuario',
        ),
    ]
